services:
  # Application
  app:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - database
    networks:
      - api-network
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"

  # Web Server
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - /etc/letsencrypt/live/api.decoskin.kz/fullchain.pem:/etc/letsencrypt/live/api.decoskin.kz/fullchain.pem:ro
      - /etc/letsencrypt/live/api.decoskin.kz/privkey.pem:/etc/letsencrypt/live/api.decoskin.kz/privkey.pem:ro

    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    networks:
      - api-network
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"

  # SSL
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  # Database
  database:
    image: mysql:8.0
    volumes:
      - .:/var/www
      - dbdata:/var/lib/mysql
      - ./docker/.bashrc:/root/.bashrc
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 33061:3306
    networks:
      - api-network
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"

  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - 8080:80
    networks:
      - api-network
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"

volumes:
  dbdata:

networks:
  api-network:
    external: true
    name: api-network